In [86]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

import keras
from keras.models import Sequential
from keras.layers import Dense

In [48]:
df = pd.read_csv('Churn_Modelling.csv')

In [49]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [50]:
x = df.iloc[:,3:13].values
y = df.iloc[:, 13].values

In [51]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [52]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [53]:
#Encoding categorical data

In [54]:
#label_enc = LabelEncoder()
#x[:, 1] = label_enc.fit_transform(x[:, 1])
#x[:, 2] = label_enc.fit_transform(x[:, 2])

In [55]:
#x[:, 1]

In [56]:
#x[:, 2]

In [57]:
#x

In [58]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [1])], remainder = 'passthrough')
x = ct.fit_transform(x)

In [63]:
#Still Gender is not encoded
x[:7]

array([[1.0, 0.0, 0.0, 619, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 'Female', 41, 1, 83807.86, 1, 0, 1,
        112542.58],
       [1.0, 0.0, 0.0, 502, 'Female', 42, 8, 159660.8, 3, 1, 0,
        113931.57],
       [1.0, 0.0, 0.0, 699, 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 850, 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [0.0, 0.0, 1.0, 645, 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [1.0, 0.0, 0.0, 822, 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8]],
      dtype=object)

In [64]:
labelencoder_x_2=LabelEncoder()
x[:,4]=labelencoder_x_2.fit_transform(x[:,4])

In [66]:
#Now gender is encoded
x[:7]

array([[1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [1.0, 0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [1.0, 0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [0.0, 0.0, 1.0, 645, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [1.0, 0.0, 0.0, 822, 1, 50, 7, 0.0, 2, 1, 1, 10062.8]],
      dtype=object)

In [67]:
# To avoid dummy variable trap
x = x[:, 1:]

In [68]:
x[:7]

array([[0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [0.0, 1.0, 608, 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [0.0, 0.0, 502, 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [0.0, 0.0, 699, 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [0.0, 1.0, 850, 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [0.0, 1.0, 645, 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [0.0, 0.0, 822, 1, 50, 7, 0.0, 2, 1, 1, 10062.8]], dtype=object)

In [69]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [70]:
# standard scaler

In [71]:
sc = StandardScaler()
x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

In [73]:
# Initiate ANN
classifier = Sequential()

In [76]:
# Adding the input layer and first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [77]:
# Adding the 2nd hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [78]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [80]:
# Compiling ANN
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [82]:
# Fitting ANN to training set
classifier.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4983 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4984 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.5011 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.5089 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - ETA: 0s - loss: 0.5075 - accuracy: 0.79 - 1s 129us/step - loss: 0.5064 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 134us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 10/100


Epoch 78/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.5059 - accuracy: 0.7960
Epoch 79/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.5059 - accuracy: 0.7960
Epoch 80/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.5059 - accuracy: 0.7960
Epoch 81/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.5059 - accuracy: 0.7960
Epoch 82/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 83/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 84/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.5059 - accuracy: 0.7960
Epoch 85/100
8000/8000 [==============================] - 1s 135us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 86/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.5059 - accuracy: 0.7960
Epoch 87/100
8000/8000 [======================

In [84]:
y_predict = classifier.predict(x_test)
y_predict

array([[0.20463014],
       [0.20463014],
       [0.20463014],
       ...,
       [0.20463014],
       [0.20463014],
       [0.20463014]], dtype=float32)

In [85]:
y_predict = (y_predict > 0.5)
y_predict

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [87]:
cm = confusion_matrix(y_test, y_predict)
cm

array([[1595,    0],
       [ 405,    0]], dtype=int64)

In [88]:
1595/2000

0.7975